#!/bin/sh

echo '========================================='
echo "Running PostRm--> $0 $@"
echo '========================================='
dpkg -r docker-engine
rm -rf /usr/bin/docker-machine
rm -rf /usr/bin/docker-compose
echo '============================ end PostRm ='
