#!/bin/sh
echo "Running PostInst--> $0 $@"
echo "========================================="
systemctl docker restart
systemctl enable cluster-start.service
systemctl enable cluster-stop.service
echo "========================== end PostInst ="
