#!/bin/sh
. /etc/lsb-release
DOCKER_ENGINE_VER='1.9.1-0'
DOCKER_MACHINE_VER='0.5.6'
DOCKER_COMPOSE_VER='1.5.2'

echo '========================================='
echo "Running PostInst--> $0 $@"
echo '========================================='

echo '\n==== Installing linux-image-extra ====='
apt-get install -y linux-image-extra-`uname -r`

echo '\n====== Installing Docker Engine ======='
curl https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_$DOCKER_ENGINE_VER~"$DISTRIB_CODENAME"_amd64.deb > /tmp/docker-engine.deb
dpkg -i /tmp/docker-engine.deb
rm -rf /tmp/docker-engine.deb

echo '\n====== Installing Docker Machine ======'
curl -L https://github.com/docker/machine/releases/download/v$DOCKER_MACHINE_VER/docker-machine_linux-amd64 > /usr/bin/docker-machine
chmod +x /usr/bin/docker-machine

echo '\n====== Installing Docker Compose ======'
curl -L https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VER/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose
chmod +x /usr/bin/docker-compose

echo '\n========== Enabling Services =========='
systemctl restart docker
systemctl enable cluster-start.service
systemctl enable cluster-stop.service
echo '========================== end PostInst ='
