consul:
  image: progrium/consul
  restart: always
  ports:
    - "8400:8400"
    - "8500:8500"
    - "53:53"
    - "8301:8301"
    - "8302:8302"
  net: host
  log_opt:
    max-size: "10m"
    max-file: "5"
  command: -server -bind ${MACHINE_IP} ${CONSUL_QUORUM_OR_JOIN}
swarm-manager:
  image: swarm
  ports:
    - 2378:2375
  command: manage --replication --advertise ${MACHINE_IP}:2378 consul://${MACHINE_IP}:8500/${CLUSTER_NAME}
swarm-agent:
  image: swarm
  command: join --advertise ${MACHINE_IP}:2375 consul://${MACHINE_IP}:8500/${CLUSTER_NAME}


