consul:
  image: progrium/consul
  restart: always
  ports:
    - "8400:8400"
    - "8500:8500"
    - "53:53"
    - "8301:8301"
    - "8302:8302"
  net: host
  log_opt:
    max-size: "10m"
    max-file: "5"
  command: -server -bind ${MACHINE_IP} ${CONSUL_QUORUM_OR_JOIN}
swarm-manager:
  image: swarm
  restart: always
  ports:
    - 3376:2375
  volumes:
    - ${DOCKER_MACHINE_CERTS}:/docker-machine-certs
  command: >
    manage
    --replication
    --advertise ${MACHINE_IP}:2378
    --tlsverify
    --tlscacert=/docker-machine-certs/ca.pem
    --tlscert=/docker-machine-certs/server.pem
    --tlskey=/docker-machine-certs/server-key.pem
    consul://${MACHINE_IP}:8500/${CLUSTER_NAME}
  log_opt:
    max-size: "10m"
    max-file: "5"
swarm-agent:
  image: swarm
  restart: always
  command: join --advertise ${MACHINE_IP}:2376 consul://${MACHINE_IP}:8500/${CLUSTER_NAME}
  log_opt:
    max-size: "10m"
    max-file: "5"


